evaluationDashboard/dashboard/urls.py
from django.urls import path

from dashboard.views import load_file, index, select_file, statistics, graphs, load_data

# App name is used in templates to call specific view via url command
# For example: href="{% url 'dashboard:index' ...%}"
app_name = "dashboard"

urlpatterns = [
    path('', index.as_view(), name='index'),
    path('graphs/', graphs.as_view(), name='graphs'),
    path('statistics/', statistics.as_view(), name="statistics"),
    path('load_file/', load_file.as_view(), name='load_file'),
    path('select_file/', select_file.as_view(), name='select_file'),
    path('load_data/', load_data.as_view(), name='load_data'),
]

evaluationDashboard/evaluationDashboard/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("dashboard/", include("dashboard.urls")),
    #path("table_data/", include("table_data.urls")),
    #path("graphs/", include("graphs.urls")),
    #path("statisticApp/", include("statisticApp.urls")),
    path('admin/', admin.site.urls),
]

evaluationDashboard/dashboard/models.py
from django.db import models

# Create your models here.
class UploadTable(models.Model):
    file = models.FileField(upload_to="documents/")

class UploadTSV(models.Model):
    data = models.JSONField()

evaluationDashboard/dashboard/forms.py
from django import forms
from .models import UploadTable


class UploadTableForm(forms.ModelForm):
    class Meta:
        model = UploadTable
        fields = ['file']

class UploadTSVForm(forms.Form):
    file = forms.FileField()

def getFileNames():
    return {i.file: i.file for i in UploadTable.objects.all()}

class FileSelectForm(forms.Form):
    fileName = forms.ChoiceField(label="", choices=getFileNames)

evaluationDashboard/dashboard/views.py
# Import url and rendering stuff
from django.shortcuts import render, HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import View
from django.template.loader import render_to_string
from django.http import JsonResponse

# Import forms
from .forms import UploadTableForm, FileSelectForm, UploadTSVForm

# Import models
from .models import UploadTSV

# Import data processing stuff
import pandas as pd

# Import pagination
from django.core.paginator import Paginator

import json
import csv


# Main page view

class index(View):
    template = 'dashboard/index.html'
 


    def get(self, request):
            
                return render(request, self.template)
            

class load_data(View):
    
    def get(self, request):
        if ('selectedFile' in request.session):
            filePath = request.session['selectedFile']

            # Read header of the tsv
            header = pd.read_csv(filePath, nrows=0, sep="\t")

            # Read the rest of available data
            df = pd.read_csv(filePath, sep="\t", index_col=0, header=0)

            # Extract header data to list
            header = header.columns.tolist()

            # Extract the rest of the data to list 
            data = df.to_csv()
            dict_data = []

            with open(filePath, "r") as table:
                reader = csv.DictReader(table, delimiter="\t")
                for row in reader:
                    dict_data.append(row)
                json_file = json.dumps(dict_data)

            context = {"values":dict_data}
                
            return JsonResponse(context)
        else:
            return JsonResponse({"header":"File not found"})



class load_file(View):
    #formClass = UploadTableForm
    formClass = UploadTSVForm
    template = "dashboard/loadFile.html"
    model = UploadTSV

    def get(self, request):
        context = {"form":self.formClass}
        return render(request, self.template, context)
    
    def post(self, request):
        form = self.formClass(request.POST, request.FILES)
        if form.is_valid():
            df = pd.read_csv(request.FILES['file'], sep="\t")
            json_file = df.to_json(orient="records")
            instance = UploadTSV(data=json_file)
            instance.save()
            return HttpResponseRedirect(reverse('dashboard:index'))
        

class select_file(View):
    formClass = FileSelectForm
    template = 'dashboard/selectFile.html'

    def get(self, request):
        context = {"form":self.formClass}
        return render(request, self.template, context)
    
    def post(self, request):
        form = self.formClass(request.POST)
        if form.is_valid():
            fileName = form.cleaned_data['fileName']
            filePath = 'media/' + fileName
            request.session['selectedFile'] = filePath
            return HttpResponseRedirect(reverse('dashboard:index')) 

class graphs(View):
    
    def get(self, request):

        return render(request, 'dashboard/graphs.html')


class statistics(View):
    def get(self, request):
        
        return render(request, 'dashboard/statistics.html')

evaluationDashboard/dashboard/templates/dashboard/graphs.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Evaluation Dashboard</title>
    {% load static %}

    <!--Load css stylesheet-->
    <link rel="stylesheet" href="{% static '/dashboard/style.css' %}">
    
</head>


<body>
    <!--Links to main parts of dashboard-->
    <div class="header">
        <div class="links">
            <a href="{% url 'dashboard:index'%}">Overview</a>
            <a href="{% url 'dashboard:graphs'%}">Graphs</a>
            <a href="{% url 'dashboard:statistics'%}">Statistics</a>
        </div>  


            
        <div class="fileSelect">
        <!--Link to selecting loaded file-->
        <a href="{% url 'dashboard:select_file' %}" class="LoadFileButton">Select File</a>

        <!--Link to file uploading page-->
        <a href="{% url 'dashboard:load_file' %}" class="LoadFileButton">Load file</a>
        </div>
    </div>

    <!--Main part of graphs page-->
    <div class="main">
        <div class="sidebar">
        
        </div>
        
        <div class="verticalLine"></div>

        <div class="mainbar">
        
        </div>
        
    </div>
    
    <!--Load javascript file-->
    <script src="{% static 'dashboard/scripts.js' %}"></script>
</body>
</html>

evaluationDashboard/dashboard/templates/dashboard/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Evaluation Dashboard</title>
    {% load static %}

    <!--Load css stylesheet-->
    <link rel="stylesheet" href="{% static '/dashboard/style.css' %}">
    
</head>


<body>
    <!--Links to main parts of dashboard-->
    <div class="header">
        <div class="links">
            <a href="{% url 'dashboard:index'%}">Overview</a>
            <a href="{% url 'dashboard:graphs'%}">Graphs</a>
            <a href="{% url 'dashboard:statistics'%}">Statistics</a>
        </div>  


            
        <div class="fileSelect">

        
        <!--Link to selecting loaded file-->
        <a href="{% url 'dashboard:select_file' %}" class="LoadFileButton">Select File</a>
    
        <!--Link to file uploading page-->
        <a href="{% url 'dashboard:load_file' %}" class="LoadFileButton">Load file</a>
        </div>
    </div>

    <!--Main part of overview page-->
    <div class="main">
        <div class="sidebar">
        {{selectedValue}}
        </div>
        
        <div class="verticalLine"></div>

        <!--Place for table to load-->
        <div class="mainbar">
        
        {% if selectedData %}
            
            <table>
                <tr>
                    {% for name in header%}
                    <th>{{ name }}</th>
                    {% endfor %}
                </tr>
                {% for row in selectedData %}
                <tr>
                    {% for column in row %}
                    <td>{{ column }}</td>
                    {% endfor %}
                </tr>
                {% endfor %}
            </table>
            
            <!--Pagination for the table-->
            <div>
                {% if selectedData.has_previous %}
                    <a href="?page=1">&laquo;</a>
                    <a href="?page={{selectedData.previous_page_number}}">Previous</a>
    
                {% endif %}
    
                Page {{selectedData.number}} of {{selectedData.paginator.num_pages}}
    
                {% if selectedData.has_next %}
                    <a href="?page={{selectedData.next_page_number}}">Next</a>
                    <a href="?page={{selectedData.paginator.num_pages}}">&raquo;</a>
    
                {%endif%}
            </div>
        {%else%}
            
            <table>
                <tr>File not found</tr>
            </table>
            
        {%endif%}
        </div>
        

        
        
        
    </div>
    
    <!--Load javascript file-->
    <script src="{% static 'dashboard/scripts.js' %}"></script>
</body>
</html>

evaluationDashboard/dashboard/templates/dashboard/index_old.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Evaluation Dashboard</title>
    {% load static %}

    <!--Load css stylesheet-->
    <link rel="stylesheet" href="{% static '/dashboard/style.css' %}">

    <!-- Simples Datatables-->
    
    <link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet" type="text/css">
    <script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" type="text/javascript"></script>
    
</head>


<body>
    <!--Links to main parts of dashboard-->
    <div class="header">
        <div class="links">
            <a href="{% url 'dashboard:index'%}">Overview</a>
            <a href="{% url 'dashboard:graphs'%}">Graphs</a>
            <a href="{% url 'dashboard:statistics'%}">Statistics</a>
        </div>  


            
        <div class="fileSelect">

        
        <!--Link to selecting loaded file-->
        <a href="{% url 'dashboard:select_file' %}" class="LoadFileButton">Select File</a>
    
        <!--Link to file uploading page-->
        <a href="{% url 'dashboard:load_file' %}" class="LoadFileButton">Load file</a>
        </div>
    </div>

    <!--Main part of overview page-->
    <div class="main">
        <div class="sidebar">
        {{selectedValue}}
        </div>
        
        <div class="verticalLine"></div>

        <!--Place for table to load-->
        <div class="mainbar">
        
        {% if selectedData %}
            
            <table>
                <tr>
                    {% for name in header%}
                    <th>{{ name }}</th>
                    {% endfor %}
                </tr>
                {% for row in selectedData %}
                <tr>
                    {% for column in row %}
                    <td>{{ column }}</td>
                    {% endfor %}
                </tr>
                {% endfor %}
            </table>
            
            <!--Pagination for the table-->
            <div>
                {% if selectedData.has_previous %}
                    <a href="?page=1">&laquo;</a>
                    <a href="?page={{selectedData.previous_page_number}}">Previous</a>
    
                {% endif %}
    
                Page {{selectedData.number}} of {{selectedData.paginator.num_pages}}
    
                {% if selectedData.has_next %}
                    <a href="?page={{selectedData.next_page_number}}">Next</a>
                    <a href="?page={{selectedData.paginator.num_pages}}">&raquo;</a>
    
                {%endif%}
            </div>
        {%else%}
            
            <table>
                <tr>File not found</tr>
            </table>
            
        {%endif%}
        </div>
        

        
        
        
    </div>
    <script>
        console.log('{{ header }}')
    </script>
    
    <!--Load javascript file-->
    <script src="{% static 'dashboard/scripts.js' %}"></script>
</body>
</html>

evaluationDashboard/dashboard/templates/dashboard/loadFile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Load file</title>
    {% load static %}

    <link rel="stylesheet" href="{% static '/dashboard/loadFile.css' %}">
</head>
<body>
    <div class="formContainer">
    <form method='post' enctype="multipart/form-data" class="form">
        {% csrf_token %}
        {{form.as_div}}
        <input type="submit" value="Upload file" class="sendForm">
    </form>
    <a href="javascript:history.go(-1)">Back to main page</a>
    </div>  

    <script src="{% static 'dashboard/loadFile.js' %}"></script>
</body>
</html>

evaluationDashboard/dashboard/templates/dashboard/selectFile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Select file</title>

    {% load static %}
    <link rel="stylesheet" href="{% static '/dashboard/selectFile.css' %}">
</head>

<body>
    <div class="formContainer">
        <form method="post" action="{% url 'dashboard:select_file' %}" id="select-form">
            {% csrf_token %}
            {{form.as_div}}
        <input type="submit" value="Select">
        </form>
        <a href="javascript:history.go(-1)">Back to main page</a>
        </div>  
    
  
</body>
</html>

evaluationDashboard/dashboard/templates/dashboard/statistics.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Evaluation Dashboard</title>
    {% load static %}

    <!--Load css stylesheet-->
    <link rel="stylesheet" href="{% static '/dashboard/style.css' %}">
    
</head>


<body>
    <!--Links to main parts of dashboard-->
    <div class="header">
        <div class="links">
            <a href="{% url 'dashboard:index'%}">Overview</a>
            <a href="{% url 'dashboard:graphs'%}">Graphs</a>
            <a href="{% url 'dashboard:statistics'%}">Statistics</a>
        </div>  


            
        <div class="fileSelect">
        <!--Link to selecting loaded file-->
        <a href="{% url 'dashboard:select_file' %}" class="LoadFileButton">Select File</a>

        <!--Link to file uploading page-->
        <a href="{% url 'dashboard:load_file' %}" class="LoadFileButton">Load file</a>
        </div>
    </div>

    <!--Main part of statistics page-->
    <div class="main">
        <div class="sidebar">
        
        </div>
        
        <div class="verticalLine"></div>

        <div class="mainbar">
        
        </div>
        
    </div>
    
    <!--Load javascript file-->
    <script src="{% static 'dashboard/scripts.js' %}"></script>
</body>
</html>